import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Canvas, useThree } from "@react-three/fiber";
import Blob from "@/components/Blob";
// import {
//   Bloom,
//   DepthOfField,
//   EffectComposer,
//   Noise,
// } from "@react-three/postprocessing";
import { useEffect, useState } from "react";
import { PerspectiveCamera } from "@react-three/drei";
import { UnrealBloomPass } from "three/examples/jsm/postprocessing/UnrealBloomPass";
import { Bloom, EffectComposer } from "@react-three/postprocessing";
import { KernelSize } from "postprocessing";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [width, setWidth] = useState();
  const [height, setHeight] = useState();

  useEffect(() => {
    setWidth(window.innerWidth);
    setHeight(window.innerHeight);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Canvas>
          <PerspectiveCamera
            position={[0, 0, 2.5]}
            fov={75}
            aspect={width / height}
            near={0.01}
            far={100}
            makeDefault
          />
          <EffectComposer>
            <Bloom
              intensity={1.4}
              luminanceThreshold={0.8}
              luminanceSmoothing={0.01}
              resolutionX={width}
              resolutionY={height}
              kernelSize={KernelSize.LARGE}
            />
            {/* <Noise opacity={0.02} /> */}
            <Blob />
          </EffectComposer>
        </Canvas>
      </main>
    </>
  );
}
